### ISSUE TITLE
Debugging no longer working with current version

### ISSUE THREAD

**Issue by NuclearCookie** [gogoprog/atom-gdb#13]
I select the correct startup directory and executable. QT opens, but nothing more happens.

**Comment by gogoprog** [comment]
Do you see something in Application Output in qtcreator?

**Comment by NuclearCookie** [comment]
I believe I was not up to date with QtCreator :crying_cat_face:

**Comment by gogoprog** [comment]
So is it ok now?

**Comment by NuclearCookie** [comment]
Cannot reproduce
