### ISSUE TITLE
Save settings in a .atom-gdb file

### ISSUE THREAD

**Issue by gogoprog** [gogoprog/atom-gdb#4]
Save the binary path and the startup directory in a .atom-gdb file in the root directory

**Comment by curtisblackwell** [comment]
@gogoprog what's the `startupDirectory`? I've got it working (thanks for building it!), but not sure if this belongs in each project or somewhere else…

**Comment by gogoprog** [comment]
@curtisblackwell it is the directory in which the gdb process will be started, so it must be a per-project settings. (useful if your app tries to open relative files)

The startup directory will be asked the first time the debugging is started and will be stored in .atom-gdb.json file.

The .atom-gdb.json file will be saved in the project root directory.

Thanks for using/testing the plugin ;)
