### ISSUE TITLE
Additional features:

### ISSUE THREAD

**Issue by NuclearCookie** [gogoprog/atom-gdb#8]
A "Stop debugging" ( Shift + f5 ) would be nice. 
Also, when pressing f5, it  launches a new debugging session every time, even if you are already debugging. Could you prevent this from happening? Or stop the current debugging session and start a new one?

**Comment by gogoprog** [comment]
That's a good idea but the only thing I could do is to kill the external debugger process which won't feel "clean".

So I don't really know, what do you think?

**Comment by NuclearCookie** [comment]
I'm not sure if it won't feel clean. If you can store the pid of the program you spawned, and ask to shut it down ( SIGQUIT? ).. As for preventing to launch a new instance when you're already debugging, I think this can achieved by keeping track of the pids as well
